# Generated by Django 4.1.1 on 2022-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=280)),
                ('price', models.IntegerField(max_length=5)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='products')),
            ],
        ),
    ]
